cogs/social.py

added tweet

---

cogs/linkfetch.py
cogs/rank.py
cogs/room.py
cogs/rules.py
cogs/social.py
cogs/userrank.py
cogs/wiki.py
main.py

Right then. This is gonna need a list:
- Almost *every* Message Embed has been changed. 
- `!rank <user>` now also includes the profile picture of that user, as well as their subscription status. 
- `!rules` has been placed into an Embed instead of a code block. 
- Moto.js functionality has been ported from the main site. (as a side note, the `getMoto()` function added could do with being made a global function)
- Probably more that I've forgot

Embeds. A *LOT* of Embeds.

---

README.md
cogs/partner.py
main.py

Won't auto merge for some reason, likely README.md.
Added partner cog and `!partner` command to display partner information.

Add Partner Cog

---

cogs/partner.py

> DarkStar: Quick update on the partnered command, let's go ahead and have the code present but we'll comment it out for now. This is something that needs a fair amount of discussion within the staff and for now we're looking to hold off on discord links other than HTB's
Ask and ye shall receive

Partner Change

---

cogs/fun.py
config/dark.json
main.py

+Fixed the welcome message, rules are now sent in DM and the welcoming message itself is fixed.
+Added dark, skidy and ashu's quotes fun commands.

Fixed welcome message, added fun commands (skidy, ashu, dark)

---

config/quotes.json
config/verify_steps.json
main.py

+Added kali lincox quote (rare).
+Added DM on joining about the verify command.

Added VERIFY instructions and kali lincox special quote.

---

cogs/room.py
main.py

+Added SUCCESS and ERROR tags to cog loading.
+Added VPN command.

+VPN command; +SUCCESS/ERROR tag when cogs load

---

cogs/devrole.py
cogs/fun.py
cogs/gtfobins.py
cogs/help.py
cogs/jira.py
cogs/rank.py
cogs/rolesync.py
cogs/room.py
cogs/rules.py
cogs/social.py
cogs/userrank.py
cogs/vote.py
cogs/wiki.py
main.py

+Added cooldown to error message in ROLESYNC.
+Added description/usage to every command
+Added custom help command (and staff command)

+Custom help; +Desc/usage to all cmds; +Cooldown to verify cmd

---

cogs/fun.py

Reverts DarkStar7471/THM-Bot#74

Revert "Added to Fun and Jira"

---

.gitignore
cogs/giveaway.py
cogs/help.py
cogs/room.py
main.py

+Writeup command
+Multivpn command
+Newroom command
+Implemented giveaway command
~Disabled broken cogs
~Removed wrong usage of help and staff commands
Updated .gitignore

New room commands. Added giveaway command. Disabled broken cogs.

---

cogs/faq.py
cogs/welcome.py
config/strings.json

- Fixed mulltivpn messages: Content was not displayed properly.
- Fixed welcome "how to verify": Keys were displayed instead of the content.

~Fixed multivpn and welcome "how to verify"

---

cogs/rolesync.py
config/strings.json

We cannot register two tokens for the same account anymore.
https://github.com/DarkStar7471/THM-Bot/issues/100

~Fixed verifying multitoken

---

cogs/rolesync.py
config/strings.json

A follow up of https://github.com/DarkStar7471/THM-Bot/pull/101

+Cannot verify more than one discord account per token

---

cogs/rolesync.py

Follow up of https://github.com/DarkStar7471/THM-Bot/issues/100

~Fixed token check

---

config/strings.json

Needed sudo killall openvpn, and there will be 2 processes that appear to be openvpn, one is a sudo process and one is an openVPN process

Update MultiVPN for non root kali

---

cogs/leaderboard.py
cogs/userrank.py
libs/thm_api.py

This PR optimizes API calls in `!rank`, `!leaderboard` and `!monthly`.
Closes #97

Optimizations to THM API calls

---

config/strings.json

Updated the `strings.json` to include the amended rule 6, in addition, to rule 15 to solve issue #112.
Tested locally & in dev server - should be a quick merge after looking over 👍

Update rules 6 and 15 for #112

---

libs/thm_api.py

This PR fixes the leaderboards API call as THM changed it.
Closes #120

Fix !monthly

---

cogs/devrole.py
cogs/giveaway.py
cogs/gtfobins.py
cogs/jira.py
cogs/room.py
cogs/staff_vote.py
cogs/stats.py
config/config.json
config/strings.json
libs/command_manager.py

+Added CM vote clear;
+Added channel checks to command_manager;
+Fixed cogs related to strings modifications

+Added CM vote clear; +Added channel checks to command_manager; +Fixed cogs related to strings modifications

---

cogs/room.py
config/config.json
config/strings.json
libs/thm_api.py
libs/utils.py

This PR implements `!randomroom`
Closes #89

Implement !randomroom

---

cogs/exploit-db.py

Auto-detect searches for CVEs in !exploit

-CVE Flag autodetection

---

README.md
cogs/faq.py
config/strings.json

Added a !vpnscript that will close #128
It provides an embed to the THM VPN Troubleshooting script which has been heavily requested.
--
Also, rule 16 which was created  on 24/07/2020 to the bot's !rule # feature
Many thanks!

Added !vpnscript & added rule 16

---

config/strings.json

Added links to mentioned channels in !rules 11 and !rules 14
Added links to mentioned help channels (and removed old reference to community-help) to the welcome message as well

Added direct link to channels mentioned in strings

---

README.md
cogs/leaderboard.py
config/strings.json
libs/thm_api.py

Outline of the changes:
- Moved the page selection from the leaderboard api function to the image generating one
- Added checks for leaderboard entry count when there aren't a multiple of 5 users per page (useful for #130 )
- Combined both image generating functions to one with arguments to avoid code reuse
- Removed two variables from the image generating function since they were not used anymore 
- Removed a duplicate string (reason: the commands do the same thing, monthly only has few little details different and this way it's easier to keep the shared code clean)
The code has been tested and is working without a problem
Closes #113

Fixed leaderboard pages and removed duplicate code

---

README.md
cogs/fun.py

I've added a bit of code that shows the cooctus emoji when !cooctus is invoked.
I've asked and ~5 people were interested in using cooctus. As per the README, the bot shouldn't have more than 10 fun commands at once and as of yet there are only 9. So cooctus could fill in the missing spot.
PS: Sorry for the double PR, I made the URL for the image more permanent.

Added !cooctus

---

libs/config.py

Properly reads files with context manager
Cleaned up variable names for consistency

Fixed file i/o & variable names

---

cogs/fun.py

Ninja made an upscaled version of the cooctus. I've uploaded the image to Imgur and changed the link in the bot. The link is now in the same format as the other Imgur links used in the bot (eg. Skidy and Dark).

Upscaled Cooctus image

---

cogs/leaderboard.py

Changed class from Cog to Leaderboard
Added docstring with a quick description of functionality

Fixed mis-named Class; Added docstring

---

cogs/room.py

Changed the new room listener to compare the last released room to the new room via code instead of title, fixing issue https://github.com/DarkStar7471/THM-Bot/issues/143
Also added docstring for cog

New room releases now compared by code, not title

---

cogs/fun.py

Outline of the changes:
- Replaced the static shibe and spaniel links with links fetched from dog.api
Closes #88

Add a random source for !shibe and !spaniel

---

cogs/userrank.py
config/config.json

Outline of the changes:
- Restricted usage of !rank to #bot_commands
Closes #159

Limit !rank usage to just #bot-commands

---

cogs/docs.py
cogs/social.py
config/strings.json

The bot provides an embed to the THM "Free Path" post on the THM blog to close issue #181 
+ I've updated `!docs room-notes` to give the URL to the category for all topics related to room creation, rather than a specific one.
+ Updated `!docs room_review` URL to link to the new room creating & testing guidelines
+ I've also added the THM Blog to the socials cog so that people can do `!blog` similar to `!reddit`, etc
Tested in Horshark dev server, no new code perse - just copy and paste from existing with slight changes and a few string changes

Included "Free Path" as Docs topic and minor housekeeping

---

cogs/rolesync.py

Issues:
https://github.com/thm-community/thm-discord-bot/issues/186
Changed server.get_member() to server.fetch_member() since discord api changed caching.

Fix verify

---

cogs/docs.py
cogs/social.py
config/strings.json

1. PR to include the bug bounty programme on docs cog !docs bug-bounty
2. PR to include the THM Store in the socials cog !shop
3. PR to include the THM support email in the social cog !email

Add !shop, !email and !docs bug-bounty

---

README.md
cogs/fun.py

Added a little method extraction refactorization with commands that use muir's hosted images.

THM-BOT [legndery] add !reno command in fun cog and update the readme file

---

cogs/moderation.py
config/config.json
config/strings.json
libs/database.py
libs/thm_api.py

Outline of the changes:
- Refactored libs/database.py (replaced string concatenation with format strings)
- Added a `get_user_by_token` function to libs/thm_api.py
- Added !lookup command allowing user lookups by using thm tokens, discord IDs, discord mentions and discord usernames
Closes #157

Token lookup implementation

---

README.md
cogs/room.py
config/strings.json

**Outline of changes**
- Tidying up the code
- Adding type and free to use status in the announcement message

dev: adding subscriber or free walkthrough/challenge to the new room announcement
